
UPDATE onboarding_steps SET target_element = '[data-tour="upload-version"]', content = 'Sube una nueva versión del plano. La versión anterior quedará registrada en el histórico pero solo la nueva será válida para obra.' WHERE id = '82331f29-69f0-4290-a082-b78ecc14b13c';
UPDATE onboarding_steps SET target_element = '[data-tour="upload-version"]', content = 'Al subir una versión nueva, la anterior queda automáticamente en el histórico. Solo la nueva es válida para obra.' WHERE id = 'd008654e-4ad4-40e2-9a93-d98f56fc94b1';
UPDATE onboarding_steps SET target_element = '[data-tour="conformity-section"]', content = 'El plano se confirma cuando cada agente del proyecto firma su conformidad individual. Cada rol tiene su casilla visible.' WHERE id = 'd82b6a0a-5f88-4422-bc78-fbfcc8bb4f33';
UPDATE onboarding_steps SET target_element = '[data-tour="conformity-section"]', content = 'El plano solo se da por Confirmado cuando cada rol implicado completa su validación individual.' WHERE id = '38d47dbb-cd22-4cd7-975a-8270fc1c60f1';
UPDATE onboarding_steps SET target_element = '[data-tour="conformity-section"]', content = 'Revisa el plano y firma tu conformidad. Tu validación queda registrada con marca temporal y geolocalización.' WHERE id = 'a61227dc-b42e-41c3-aca2-0aedc413e055';
UPDATE onboarding_steps SET target_element = '[data-tour="conformity-section"]', content = 'Revisa los planos y firma tu conformidad como Coordinador de Seguridad. Tu validación queda registrada.' WHERE id = 'a90db61e-cfef-4158-9bdb-ea213b6dc12c';
UPDATE onboarding_steps SET target_element = '[data-tour="conformity-section"]', content = 'Consulta los planos vigentes y firma tu conformidad tras revisarlos.' WHERE id = '00133b44-1695-40d8-bd2f-cb76eb956d45';
UPDATE onboarding_steps SET target_element = '[data-tour="cost-signature-panel"]', content = 'Revisa las certificaciones pendientes. Selecciona un documento para ver la previsualización y acceder a la firma técnica.' WHERE id = 'd694c28d-f2cb-48d3-9a7b-5126b4b9ac63';
UPDATE onboarding_steps SET target_element = '[data-tour="cost-signature-panel"]', content = 'Carga tu certificado (.pfx/.p12) e introduce tu contraseña. El sistema recordará la contraseña para futuras firmas con este certificado.' WHERE id = 'f1b11697-c5b9-474a-8424-4b23d8713d92';
UPDATE onboarding_steps SET target_element = '[data-tour="cost-signature-panel"]', content = 'Alternativa: firma válida con hash, huella y geolocalización (excepto para certificaciones oficiales, donde se exige certificado digital).' WHERE id = '5a775259-3343-493e-83d8-f355085e050a';
UPDATE onboarding_steps SET target_element = '[data-tour="cost-signature-panel"]', content = 'Revisa y firma técnicamente las certificaciones ya validadas por el DEM.' WHERE id = 'd00cbdb9-1787-4d59-a24b-5ce813f6445b';
UPDATE onboarding_steps SET target_element = '[data-tour="cost-signature-panel"]', content = 'Carga tu certificado (.pfx/.p12). El sistema recordará la contraseña.' WHERE id = '27fc84e1-825e-41ff-a4a6-c5410d31914b';
UPDATE onboarding_steps SET target_element = '[data-tour="cost-signature-panel"]', content = 'Firma válida con hash, huella y geolocalización (no válida para certificaciones oficiales).' WHERE id = '9a5f14d0-f34e-408a-be99-d90dc7909f98';
UPDATE onboarding_steps SET target_element = '[data-tour="cost-signature-panel"]', content = 'Revisa las certificaciones aprobadas y autoriza su pago.' WHERE id = '0fb81328-7ce7-41c3-b7e4-6a88eee95fda';
UPDATE onboarding_steps SET target_element = '[data-tour="cost-signature-panel"]', content = 'Usa tu certificado digital para firmar la autorización de pago.' WHERE id = 'f29bad72-58e1-40fd-beb9-43d913008e3d';
DELETE FROM user_onboarding_status;
